[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "scipy-tutorial-proposal-2025"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks.install]
description = "Install pre-commit into the Git hooks directory"
cmd = "pre-commit install"

[tasks.lint]
description = "Run 'pre-commit run --all-files'"
cmd = "pre-commit run --all-files"

[tasks.start]
depends-on = ["install", "lint"]

[dependencies]
pre-commit = ">=4.1.0"
